# Generated by Django 3.0.3 on 2020-03-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwtproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='image',
            field=models.ImageField(default='', upload_to='fwtproject/images'),
        ),
    ]
