# Generated by Django 3.0.3 on 2020-03-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwtproject', '0002_tours_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='image',
            field=models.ImageField(default='', upload_to='img/tours'),
        ),
    ]
