# Generated by Django 3.0.3 on 2020-03-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwtproject', '0003_auto_20200329_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='dn',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='sdesc',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
