# Generated by Django 3.0.3 on 2020-03-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwtproject', '0004_auto_20200330_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='state',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
