# Generated by Django 3.0.3 on 2020-04-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwtproject', '0008_tours_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='category',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
