# Generated by Django 3.0.3 on 2020-04-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwtproject', '0009_tours_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='adults',
            field=models.IntegerField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='children',
            field=models.IntegerField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
