# Generated by Django 3.0.3 on 2020-04-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwtproject', '0010_auto_20200402_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=5000)),
                ('destination', models.CharField(max_length=20)),
            ],
        ),
    ]
