# Generated by Django 3.0.3 on 2020-04-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwtproject', '0011_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='imagebig',
            field=models.ImageField(default='', upload_to='img/blog'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='imagesmall1',
            field=models.ImageField(default='', upload_to='img/blog'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='imagesmall2',
            field=models.ImageField(default='', upload_to='img/blog'),
        ),
    ]
