# Generated by Django 3.0.3 on 2020-04-02 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fwtproject', '0012_auto_20200402_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='nViews',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=20)),
                ('blogid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fwtproject.blogs')),
            ],
        ),
    ]
