# Generated by Django 3.0.3 on 2020-04-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwtproject', '0013_auto_20200403_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='body',
            field=models.TextField(max_length=5000),
        ),
    ]
