# Generated by Django 3.0.3 on 2020-04-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwtproject', '0014_auto_20200403_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='about',
            field=models.TextField(max_length=10000),
        ),
    ]
